# Generated by Django 4.2.4 on 2024-10-15 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('entreprise', 'Entreprise')], default='entreprise', max_length=20)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_offre', models.CharField(max_length=30, null=True)),
                ('prix', models.FloatField(null=True)),
                ('description', models.TextField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=30, null=True)),
                ('nif', models.CharField(max_length=30, null=True)),
                ('stat', models.CharField(max_length=30, null=True)),
                ('localisation', models.CharField(max_length=50, null=True)),
                ('proprio', models.CharField(max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='media/logo/')),
                ('nb_avis', models.IntegerField(default=0)),
                ('nb_client', models.IntegerField(default=0)),
                ('nb_partenaire', models.IntegerField(default=0)),
                ('texte_bienvenue', models.TextField(null=True)),
                ('intro_service', models.TextField(null=True)),
                ('intro_a_propos', models.TextField(null=True)),
                ('texte_a_propos', models.TextField(null=True)),
                ('texte_pourquoi', models.TextField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_entreprise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=50, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdd_client', to='hostease.infoentreprise')),
            ],
        ),
    ]
