# Generated by Django 4.2.4 on 2024-10-03 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('mail', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=30, null=True)),
                ('mot_de_passe', models.CharField(max_length=30, null=True)),
                ('nif', models.CharField(max_length=30, null=True)),
                ('stat', models.CharField(max_length=30, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('localisation', models.CharField(max_length=50, null=True)),
                ('proprio', models.CharField(max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='media/logo/')),
                ('nb_avis', models.IntegerField(null=True)),
                ('nb_client', models.IntegerField(null=True)),
                ('nb_partenaire', models.IntegerField(null=True)),
                ('texte_bienvenue', models.TextField(null=True)),
                ('intro_service', models.TextField(null=True)),
                ('intro_a_propos', models.TextField(null=True)),
                ('texte_a_propos', models.TextField(null=True)),
                ('texte_pourquoi', models.TextField(null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_offre', models.CharField(max_length=30, null=True)),
                ('prix', models.FloatField(null=True)),
                ('description', models.TextField(max_length=400, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_offre', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=50, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdd_client', to='hostease.entreprise')),
            ],
        ),
    ]
