# Generated by Django 4.2.4 on 2024-10-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostease', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contact',
        ),
        migrations.AddField(
            model_name='infoentreprise',
            name='contact',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
