# Generated by Django 4.2.4 on 2024-10-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostease', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='admin',
        ),
    ]
