# Generated by Django 4.2.4 on 2024-11-05 15:59

from django.db import migrations, models
import django.utils.timezone
import hostease.models


class Migration(migrations.Migration):

    dependencies = [
        ('hostease', '0002_offreentreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreentreprise',
            name='date_begin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offreentreprise',
            name='date_exp',
            field=models.DateTimeField(default=hostease.models.one_year_from_now),
        ),
    ]
