# Generated by Django 4.2.4 on 2024-10-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostease', '0002_remove_customuser_contact_infoentreprise_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoentreprise',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
    ]
