# Generated by Django 4.2.4 on 2024-11-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostease', '0003_offreentreprise_date_begin_offreentreprise_date_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreentreprise',
            name='motif_payement',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='offreentreprise',
            name='ref_payement',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
