# Generated by Django 4.2.4 on 2024-11-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostease', '0004_offreentreprise_motif_payement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreentreprise',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_offre', to='hostease.offre'),
        ),
    ]
